apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-config
    files:
      - nginx/default.conf

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
